# Generated by Django 3.2.4 on 2021-06-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHerbServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/iHerbServer/user_avatars/default_avatar.png', null=True, upload_to='iHerbServer/user_avatars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=255, null=True, verbose_name='UUID'),
        ),
    ]
