# Generated by Django 2.2.2 on 2021-06-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iHerbServer', '0004_auto_20210619_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_answer', to='iHerbServer.Question'),
        ),
    ]
