# Generated by Django 2.2.2 on 2021-06-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iHerbServer', '0004_auto_20210619_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
