# Generated by Django 2.2.2 on 2021-06-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iHerbServer', '0005_answer_next_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_final',
            field=models.BooleanField(default=False, null=True, verbose_name='Финальный вопрос'),
        ),
    ]
