# Generated by Django 2.2.2 on 2021-06-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iHerbServer', '0005_remove_user_phone'),
        ('iHerbServer', '0006_question_is_final'),
    ]

    operations = [
    ]
